server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  auth_basic "MGT 404 course access";
  auth_basic_user_file /etc/nginx/.htpasswd;

  location / {
    try_files $uri $uri/ =404;
  }

  location ~* \.(?:css|js|svg|png|jpg|jpeg|gif|webp|ico)$ {
    expires 1h;
    add_header Cache-Control "public";
    try_files $uri =404;
  }
}
